version: 2.1

commands:
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            bundle install

jobs:
  spec_2_4:
    docker:
      - image: circleci/ruby:2.4.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - install_dependencies
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            bundle exec rspec \
              --format progress
  spec_2_5:
    docker:
      - image: circleci/ruby:2.5.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - install_dependencies
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            bundle exec rspec \
              --format progress
  spec_2_6:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - install_dependencies
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            bundle exec rspec \
              --format progress

workflows:
  spec_all:
    jobs:
      - spec_2_4
      - spec_2_5
      - spec_2_6
